// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.jshop.domain;

import com.malsolo.jshop.domain.Brand;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect BrandDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BrandDataOnDemand: @Component;
    
    private Random BrandDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Brand> BrandDataOnDemand.data;
    
    public Brand BrandDataOnDemand.getNewTransientBrand(int index) {
        com.malsolo.jshop.domain.Brand obj = new com.malsolo.jshop.domain.Brand();
        java.lang.String name = "name_" + index;
        if (name.length() > 50) {
            name  = name.substring(0, 50);
        }
        obj.setName(name);
        obj.setDescription("description_" + index);
        return obj;
    }
    
    public Brand BrandDataOnDemand.getSpecificBrand(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Brand obj = data.get(index);
        return Brand.findBrand(obj.getId());
    }
    
    public Brand BrandDataOnDemand.getRandomBrand() {
        init();
        Brand obj = data.get(rnd.nextInt(data.size()));
        return Brand.findBrand(obj.getId());
    }
    
    public boolean BrandDataOnDemand.modifyBrand(Brand obj) {
        return false;
    }
    
    public void BrandDataOnDemand.init() {
        data = com.malsolo.jshop.domain.Brand.findBrandEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Brand' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.malsolo.jshop.domain.Brand>();
        for (int i = 0; i < 10; i++) {
            com.malsolo.jshop.domain.Brand obj = getNewTransientBrand(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
