// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.jshop.domain;

import com.malsolo.jshop.domain.BrandDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BrandIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BrandIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BrandIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: BrandIntegrationTest: @Transactional;
    
    @Autowired
    private BrandDataOnDemand BrandIntegrationTest.dod;
    
    @Test
    public void BrandIntegrationTest.testCountBrands() {
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to initialize correctly", dod.getRandomBrand());
        long count = com.malsolo.jshop.domain.Brand.countBrands();
        org.junit.Assert.assertTrue("Counter for 'Brand' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BrandIntegrationTest.testFindBrand() {
        com.malsolo.jshop.domain.Brand obj = dod.getRandomBrand();
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.Brand.findBrand(id);
        org.junit.Assert.assertNotNull("Find method for 'Brand' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Brand' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BrandIntegrationTest.testFindAllBrands() {
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to initialize correctly", dod.getRandomBrand());
        long count = com.malsolo.jshop.domain.Brand.countBrands();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Brand', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.malsolo.jshop.domain.Brand> result = com.malsolo.jshop.domain.Brand.findAllBrands();
        org.junit.Assert.assertNotNull("Find all method for 'Brand' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Brand' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BrandIntegrationTest.testFindBrandEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to initialize correctly", dod.getRandomBrand());
        long count = com.malsolo.jshop.domain.Brand.countBrands();
        if (count > 20) count = 20;
        java.util.List<com.malsolo.jshop.domain.Brand> result = com.malsolo.jshop.domain.Brand.findBrandEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Brand' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Brand' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BrandIntegrationTest.testFlush() {
        com.malsolo.jshop.domain.Brand obj = dod.getRandomBrand();
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.Brand.findBrand(id);
        org.junit.Assert.assertNotNull("Find method for 'Brand' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBrand(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Brand' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BrandIntegrationTest.testMerge() {
        com.malsolo.jshop.domain.Brand obj = dod.getRandomBrand();
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.Brand.findBrand(id);
        boolean modified =  dod.modifyBrand(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.malsolo.jshop.domain.Brand merged = (com.malsolo.jshop.domain.Brand) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Brand' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BrandIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to initialize correctly", dod.getRandomBrand());
        com.malsolo.jshop.domain.Brand obj = dod.getNewTransientBrand(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Brand' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Brand' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BrandIntegrationTest.testRemove() {
        com.malsolo.jshop.domain.Brand obj = dod.getRandomBrand();
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Brand' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.Brand.findBrand(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Brand' with identifier '" + id + "'", com.malsolo.jshop.domain.Brand.findBrand(id));
    }
    
}
