// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.jshop.domain;

import com.malsolo.jshop.domain.KindDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect KindIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KindIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: KindIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: KindIntegrationTest: @Transactional;
    
    @Autowired
    private KindDataOnDemand KindIntegrationTest.dod;
    
    @Test
    public void KindIntegrationTest.testCountKinds() {
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to initialize correctly", dod.getRandomKind());
        long count = com.malsolo.jshop.domain.Kind.countKinds();
        org.junit.Assert.assertTrue("Counter for 'Kind' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KindIntegrationTest.testFindKind() {
        com.malsolo.jshop.domain.Kind obj = dod.getRandomKind();
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.Kind.findKind(id);
        org.junit.Assert.assertNotNull("Find method for 'Kind' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Kind' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void KindIntegrationTest.testFindAllKinds() {
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to initialize correctly", dod.getRandomKind());
        long count = com.malsolo.jshop.domain.Kind.countKinds();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Kind', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.malsolo.jshop.domain.Kind> result = com.malsolo.jshop.domain.Kind.findAllKinds();
        org.junit.Assert.assertNotNull("Find all method for 'Kind' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Kind' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KindIntegrationTest.testFindKindEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to initialize correctly", dod.getRandomKind());
        long count = com.malsolo.jshop.domain.Kind.countKinds();
        if (count > 20) count = 20;
        java.util.List<com.malsolo.jshop.domain.Kind> result = com.malsolo.jshop.domain.Kind.findKindEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Kind' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Kind' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KindIntegrationTest.testFlush() {
        com.malsolo.jshop.domain.Kind obj = dod.getRandomKind();
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.Kind.findKind(id);
        org.junit.Assert.assertNotNull("Find method for 'Kind' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyKind(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Kind' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KindIntegrationTest.testMerge() {
        com.malsolo.jshop.domain.Kind obj = dod.getRandomKind();
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.Kind.findKind(id);
        boolean modified =  dod.modifyKind(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.malsolo.jshop.domain.Kind merged = (com.malsolo.jshop.domain.Kind) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Kind' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KindIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to initialize correctly", dod.getRandomKind());
        com.malsolo.jshop.domain.Kind obj = dod.getNewTransientKind(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Kind' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Kind' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void KindIntegrationTest.testRemove() {
        com.malsolo.jshop.domain.Kind obj = dod.getRandomKind();
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Kind' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.Kind.findKind(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Kind' with identifier '" + id + "'", com.malsolo.jshop.domain.Kind.findKind(id));
    }
    
}
