// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.jshop.domain;

import com.malsolo.jshop.domain.Kind;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect KindDataOnDemand_Roo_DataOnDemand {
    
    declare @type: KindDataOnDemand: @Component;
    
    private Random KindDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Kind> KindDataOnDemand.data;
    
    public Kind KindDataOnDemand.getNewTransientKind(int index) {
        com.malsolo.jshop.domain.Kind obj = new com.malsolo.jshop.domain.Kind();
        java.lang.String name = "name_" + index;
        if (name.length() > 50) {
            name  = name.substring(0, 50);
        }
        obj.setName(name);
        return obj;
    }
    
    public Kind KindDataOnDemand.getSpecificKind(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Kind obj = data.get(index);
        return Kind.findKind(obj.getId());
    }
    
    public Kind KindDataOnDemand.getRandomKind() {
        init();
        Kind obj = data.get(rnd.nextInt(data.size()));
        return Kind.findKind(obj.getId());
    }
    
    public boolean KindDataOnDemand.modifyKind(Kind obj) {
        return false;
    }
    
    public void KindDataOnDemand.init() {
        data = com.malsolo.jshop.domain.Kind.findKindEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Kind' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.malsolo.jshop.domain.Kind>();
        for (int i = 0; i < 10; i++) {
            com.malsolo.jshop.domain.Kind obj = getNewTransientKind(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
