// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.jshop.domain;

import com.malsolo.jshop.domain.StockLine;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect StockLineDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StockLineDataOnDemand: @Component;
    
    private Random StockLineDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<StockLine> StockLineDataOnDemand.data;
    
    public StockLine StockLineDataOnDemand.getNewTransientStockLine(int index) {
        com.malsolo.jshop.domain.StockLine obj = new com.malsolo.jshop.domain.StockLine();
        return obj;
    }
    
    public StockLine StockLineDataOnDemand.getSpecificStockLine(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        StockLine obj = data.get(index);
        return StockLine.findStockLine(obj.getId());
    }
    
    public StockLine StockLineDataOnDemand.getRandomStockLine() {
        init();
        StockLine obj = data.get(rnd.nextInt(data.size()));
        return StockLine.findStockLine(obj.getId());
    }
    
    public boolean StockLineDataOnDemand.modifyStockLine(StockLine obj) {
        return false;
    }
    
    public void StockLineDataOnDemand.init() {
        data = com.malsolo.jshop.domain.StockLine.findStockLineEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'StockLine' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.malsolo.jshop.domain.StockLine>();
        for (int i = 0; i < 10; i++) {
            com.malsolo.jshop.domain.StockLine obj = getNewTransientStockLine(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
