// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.jshop.domain;

import com.malsolo.jshop.domain.StockLineDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StockLineIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StockLineIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StockLineIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: StockLineIntegrationTest: @Transactional;
    
    @Autowired
    private StockLineDataOnDemand StockLineIntegrationTest.dod;
    
    @Test
    public void StockLineIntegrationTest.testCountStockLines() {
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to initialize correctly", dod.getRandomStockLine());
        long count = com.malsolo.jshop.domain.StockLine.countStockLines();
        org.junit.Assert.assertTrue("Counter for 'StockLine' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StockLineIntegrationTest.testFindStockLine() {
        com.malsolo.jshop.domain.StockLine obj = dod.getRandomStockLine();
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.StockLine.findStockLine(id);
        org.junit.Assert.assertNotNull("Find method for 'StockLine' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'StockLine' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StockLineIntegrationTest.testFindAllStockLines() {
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to initialize correctly", dod.getRandomStockLine());
        long count = com.malsolo.jshop.domain.StockLine.countStockLines();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'StockLine', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.malsolo.jshop.domain.StockLine> result = com.malsolo.jshop.domain.StockLine.findAllStockLines();
        org.junit.Assert.assertNotNull("Find all method for 'StockLine' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'StockLine' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StockLineIntegrationTest.testFindStockLineEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to initialize correctly", dod.getRandomStockLine());
        long count = com.malsolo.jshop.domain.StockLine.countStockLines();
        if (count > 20) count = 20;
        java.util.List<com.malsolo.jshop.domain.StockLine> result = com.malsolo.jshop.domain.StockLine.findStockLineEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'StockLine' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'StockLine' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StockLineIntegrationTest.testFlush() {
        com.malsolo.jshop.domain.StockLine obj = dod.getRandomStockLine();
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.StockLine.findStockLine(id);
        org.junit.Assert.assertNotNull("Find method for 'StockLine' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStockLine(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'StockLine' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockLineIntegrationTest.testMerge() {
        com.malsolo.jshop.domain.StockLine obj = dod.getRandomStockLine();
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.StockLine.findStockLine(id);
        boolean modified =  dod.modifyStockLine(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.malsolo.jshop.domain.StockLine merged = (com.malsolo.jshop.domain.StockLine) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'StockLine' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockLineIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to initialize correctly", dod.getRandomStockLine());
        com.malsolo.jshop.domain.StockLine obj = dod.getNewTransientStockLine(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'StockLine' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'StockLine' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StockLineIntegrationTest.testRemove() {
        com.malsolo.jshop.domain.StockLine obj = dod.getRandomStockLine();
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StockLine' failed to provide an identifier", id);
        obj = com.malsolo.jshop.domain.StockLine.findStockLine(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'StockLine' with identifier '" + id + "'", com.malsolo.jshop.domain.StockLine.findStockLine(id));
    }
    
}
