// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.jshop.domain;

import java.lang.String;

privileged aspect Kind_Roo_JavaBean {
    
    public String Kind.getName() {
        return this.name;
    }
    
    public void Kind.setName(String name) {
        this.name = name;
    }
    
}
